/**
 * CMS First-Time Setup API
 *
 * GET  /api/cms/setup - Returns { setupRequired: true/false }
 * POST /api/cms/setup - Creates the initial admin password (only works once)
 *
 * Writes CMS_ADMIN_PASSWORD (bcrypt hash) + CMS_SECRET to .env.local.
 * After setup, this endpoint becomes a no-op.
 */

import fs from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';

const ENV_PATH = path.join(process.cwd(), '.env.local');

function readEnvFile() {
  if (!fs.existsSync(ENV_PATH)) return {};
  const raw = fs.readFileSync(ENV_PATH, 'utf-8');
  const out = {};
  raw.split('\n').forEach((line) => {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, '');
  });
  return out;
}

function writeEnvFile(env) {
  const comment = `# Monolith CMS Configuration\n# Generated by setup wizard — keep this file out of Git!\n`;
  const body = Object.entries(env)
    .map(([k, v]) => `${k}=${v}`)
    .join('\n');
  fs.writeFileSync(ENV_PATH, comment + body + '\n', { mode: 0o600 });
}

function isSetupRequired() {
  // Respect env first (e.g. production), then fall back to .env.local
  if (process.env.CMS_ADMIN_PASSWORD) return false;
  const env = readEnvFile();
  return !env.CMS_ADMIN_PASSWORD;
}

export default async function handler(req, res) {
  if (req.method === 'GET') {
    return res.json({ setupRequired: isSetupRequired() });
  }

  if (req.method === 'POST') {
    if (!isSetupRequired()) {
      return res.status(409).json({ error: 'Setup already completed' });
    }

    const { password } = req.body || {};
    if (!password || typeof password !== 'string' || password.length < 8) {
      return res.status(400).json({ error: 'Password must be at least 8 characters' });
    }

    try {
      const hash = await bcrypt.hash(password, 10);
      const env = readEnvFile();
      env.CMS_ADMIN_PASSWORD = hash;
      if (!env.CMS_SECRET) {
        env.CMS_SECRET = crypto.randomBytes(32).toString('hex');
      }
      writeEnvFile(env);

      // Inject into running process so the very next login works without restart
      process.env.CMS_ADMIN_PASSWORD = hash;
      process.env.CMS_SECRET = env.CMS_SECRET;

      return res.json({ success: true });
    } catch (err) {
      console.error('[CMS Setup] Error:', err);
      return res.status(500).json({ error: 'Failed to save setup' });
    }
  }

  return res.status(405).json({ error: 'Method not allowed' });
}
